### PR TITLE
Multiple mails

### PR DESCRIPTION
**Pull request by lpinilla**
Added support for multiple mails

### CODE REVIEW

**Comment by crabvk** [comment]
Sorry, but I don't think this feature is needed. If you have two gmail accounts, why don't you just run two polybar-gmail scripts? (from different directories)

**Comment by lpinilla** [comment]
Because, in my opinion, is much cleaner to have the script to manage different mails rather than myself.

**Comment by crabvk** [comment]
The script is not intended to manage different emails. It makes just one simple thing - shows unread messages from a gmail account.

**Comment by lpinilla** [comment]
That is why I forked it and upgraded it. So it can who unread messages but leaving the option of adding multiple mails with the same commands, not creating a new instance + folders/files for each other account.

**Comment by crabvk** [comment]
I understand. You needed to add multiple accounts your way and you made it. But I don't, and I don't think users need that either.

**Comment by lpinilla** [comment]
I was just trying to improve the program, enhancing it's features so it could give more options to the users with the least impact. If any users need such feature they can find it on my branch, I'll keep it.

**Pull request closed without merging**
