### PR TITLE
Fix coloring of the text in polybar format

### PR DESCRIPTION
**Pull request by mark2185**
Only the badge should be colored, as the preview in `README.md` shows, but currently both the badge and the count are colored.

### CODE REVIEW

**Comment by crabvk** [comment]
The preview is outdated.

**Comment by mark2185** [comment]
That may be the case, but the coloring _did_ change in https://github.com/crabvk/bar-gmail/commit/22e7535aa253d54a5ee7a554c835aa3e087475b9 so this keeps it consistent with how it was before.

**Comment by crabvk** [comment]
I thought about preserving the same behaviour/coloring for Polybar, but in output for Waybar there's CSS class added to the whole text (badge + messages count), i.e. color can be changed only for the whole. So the coloring is consistent in this way.

**Comment by mark2185** [comment]
Fair enough, both approaches make sense.

I'm okay with having a fork for this since I'm used to only the icon being colored.

**Pull request closed without merging**
